services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
