version: "3.9"

services:
  frontend:
    container_name: diet-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - BACKEND_URL=http://backend:8001
    depends_on:
      - backend

  backend:
    container_name: diet-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./potts:/app/potts
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite:///app/data/dietbot.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: diet-network